import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { execFileSync } from "node:child_process";
import { collectProjectCognition, TEST_SCALE_CONTRACTS } from "../../src/init-cognition.js";

const root = fs.mkdtempSync(path.join(os.tmpdir(), "hy-init-cognition-"));
fs.mkdirSync(path.join(root, "src"), { recursive: true });
fs.mkdirSync(path.join(root, "docs"), { recursive: true });
fs.writeFileSync(path.join(root, "package.json"), JSON.stringify({ scripts: { build: "tsc", lint: "eslint .", test: "node --test" } }));
fs.writeFileSync(path.join(root, "package-lock.json"), "{}\n");
fs.writeFileSync(path.join(root, "tsconfig.json"), "{}\n");
fs.writeFileSync(path.join(root, "src", "index.ts"), "export const answer = 42;\n");
fs.writeFileSync(path.join(root, "README.md"), "# fixture\n");
fs.writeFileSync(path.join(root, "docs", "index.md"), "# docs\n");
execFileSync("git", ["init", "-b", "dev"], { cwd: root, stdio: "ignore" });
execFileSync("git", ["config", "user.name", "fixture"], { cwd: root });
execFileSync("git", ["config", "user.email", "fixture@example.invalid"], { cwd: root });
execFileSync("git", ["add", "."], { cwd: root });
execFileSync("git", ["commit", "-m", "initial"], { cwd: root, stdio: "ignore" });

execFileSync("git", ["remote", "add", "origin", "https://fixture:never-expose@example.invalid/org/repository.git"], { cwd: root });
const indexPath = path.join(root, ".git", "index");
const indexBefore = fs.readFileSync(indexPath);
const metadataOnlyTime = new Date("2030-01-02T03:04:05.000Z");
fs.utimesSync(path.join(root, "README.md"), metadataOnlyTime, metadataOnlyTime);
const cognition = collectProjectCognition(root);
assert.deepEqual(fs.readFileSync(indexPath), indexBefore, "init cognition must not refresh or rewrite the Git index");
assert.equal(cognition.schema, "hy-workflow.project-cognition.v1");
assert.equal(cognition.generatedFrom, "local-read-only");
assert.equal(cognition.profile.kind, "typescript");
assert.equal(cognition.repository.branch, "dev");
assert.equal(cognition.repository.dirty, false);
assert.ok(cognition.documentation.entryPoints.includes("README.md"));
assert.ok(cognition.documentation.entryPoints.includes("docs/index.md"));
assert.equal(cognition.documentation.externalKnowledgeAccess, false);
assert.deepEqual(cognition.verificationPlatform.scales.map(item => item.scale), ["small", "medium", "large"]);
assert.equal(cognition.repository.origin, "https://example.invalid/org/repository.git");
assert.ok(!JSON.stringify(cognition).includes("never-expose"));
assert.ok(!JSON.stringify(cognition).includes("fixture@"));
assert.deepEqual(TEST_SCALE_CONTRACTS.map(item => item.scale), ["small", "medium", "large"]);
assert.equal(cognition.verificationPlatform.scaleDecisionOwner, "skill");
assert.ok(cognition.verificationPlatform.candidateCommands.includes("npm run test"));

fs.writeFileSync(path.join(root, "src", "index.ts"), "export const answer = 43;\n");
const dirty = collectProjectCognition(root);
assert.equal(dirty.repository.dirty, true);
assert.ok(dirty.repository.changedFiles.includes("src/index.ts"));

console.log("init cognition tests passed");
